# Generated by Django 5.1.4 on 2024-12-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='position',
            new_name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='employee',
            name='date_joined',
            field=models.DateField(default='2024-12-01'),
        ),
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.CharField(default='Not Assigned', max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(default='N/A', max_length=15),
        ),
    ]
