# Generated by Django 5.1.4 on 2025-01-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_leaveapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='admin_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
