# Generated by Django 5.1.4 on 2025-01-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_leaveapplication_admin_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='leave_duration',
            field=models.CharField(choices=[('Full Day', 'Full Day'), ('Half Day', 'Half Day')], default='Full Day', max_length=10),
        ),
    ]
