# Generated by Django 5.1.4 on 2025-01-14 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_leaveapplication_leave_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaveapplication',
            old_name='end_date',
            new_name='leave_date',
        ),
        migrations.RemoveField(
            model_name='leaveapplication',
            name='start_date',
        ),
    ]
