# Generated by Django 5.1.4 on 2025-01-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_rename_end_date_leaveapplication_leave_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='applied_date',
            field=models.DateTimeField(auto_now_add=True, default='2025-01-01 00:00:00'),
            preserve_default=False,
        ),
    ]
