# Generated by Django 5.1.4 on 2025-01-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_leaveapplication_applied_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='leave_type',
            field=models.CharField(choices=[('Full Day', 'Full Day'), ('Half Day', 'Half Day')], max_length=20),
        ),
    ]
