# Generated by Django 5.1.4 on 2025-01-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_alter_leaveapplication_leave_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='leave_type',
            field=models.CharField(choices=[('Sick', 'Sick Leave'), ('Casual', 'Casual Leave'), ('Other', 'Other')], max_length=20),
        ),
    ]
