# Generated by Django 5.1.4 on 2025-01-23 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_alter_leaveapplication_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
