# Generated by Django 5.1.4 on 2025-01-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_leaveapplication_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapplication',
            name='is_active',
        ),
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
