# Generated by Django 5.1.4 on 2025-01-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_remove_leaveapplication_is_active_employee_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='employee_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='employee_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
