# Generated by Django 5.1.4 on 2025-02-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_leaveapplication_employee_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bonus_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
