# Generated by Django 5.1.4 on 2025-02-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_bonusclaim_processed_at_bonusclaim_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonusclaim',
            name='admin_remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bonusclaim',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Paid', 'Paid')], default='Pending', max_length=20),
        ),
    ]
