# Generated by Django 5.1.4 on 2025-02-05 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0018_bonusclaim_admin_remarks_alter_bonusclaim_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_bonus', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_bonus_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('leave_balance_before_claim', models.IntegerField(default=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CLAIM_REQUESTED', 'Claim Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid')], default='PENDING', max_length=15)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
