# Generated by Django 5.1.4 on 2025-02-05 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0019_bonus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bonus',
        ),
    ]
