# Generated by Django 5.1.4 on 2025-02-05 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0020_delete_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonusclaim',
            name='original_leave_balance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
